In [ ]:
'''Создайте матрицу 3 на 3, заполненную числами от 1 до 9
Прибавьте к ней матрицу с единицами на диагонале
Умножьте полученную матрицу на вектор (1, 2, 3)
Посчитайте обратную матрицу к полученной матрице'''

In [5]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.eye(3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
c = a+b
print(c)

[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]


In [9]:
x = (1, 2, 3)
y = np.dot(c,x)
print(y)

[15. 34. 53.]


In [10]:
y1 = np.linalg.inv(y)
print(y1)   # для входной матрицы у1 вычисление обратной матрицы невозможно


LinAlgError: 1-dimensional array given. Array must be at least two-dimensional